### ISSUE TITLE
Can you please provide any (interactive) tutorial for newcomer?

### ISSUE THREAD

**Issue by MeisterVenom** [google/cel-go#355]
`cel` looks great, but it seems so hard to master it and even kick off. 

It'd be really great if you guys can provide a tutorial for starter. Many thanks!

**Comment by TristonianJones** [comment]
Hi @MeisterVenom, as it happens PR #328 is the code portion of a codelab that @rachelmyers is putting together. Stay tuned!

**Comment by TristonianJones** [comment]
Awesome. @rachelmyers and I just went over the docs that go with the code and it's really coming together. I can't wait to share it with you all.

**Comment by TristonianJones** [comment]
The codelab is live! https://codelabs.developers.google.com/codelabs/cel-go/#0

**Comment by TristonianJones** [comment]
Fixed in https://github.com/google/cel-go/pull/328
