### ISSUE TITLE
Allow TypeProviders to create ref.Vals of types vs' the planner doing so

### ISSUE THREAD

**Issue by tonyhb** [google/cel-go#462]
**Feature request checklist**

- [x] There are no issues that match the desired change
- [x] The change is large enough it can't be addressed with a simple Pull Request
- [ ] If this is a bug, please file a [Bug Report](./ISSUE_TEMPLATE).

**Change**
I'm trying to override the default `types.Null` type such that comparisons to non-null types return false, vs overload errors.  This equality is checked using `evalEq` within the planner, which calls `types.Null.Equal(other ref.Val)` within the types package.  Built-in operators are deeply embedded within the interpreter;  overloading these is difficult.

Right now, built-in const values are created within the planner inside package `interpreter` (`planner.constValue`), and attribute values are created via `NativeToValue` within types package.

Maybe it would be good if the `ref.TypeProvider` interface was extended such that each type definition creates its own `ref.Val` values from the concrete values themselves.  Making each `ref.Type` responsible for creating values means we can add properly implement custom types within CEL (consts cannot be overridden right now).

This would enable full custom types to override eg. null in ~15 lines of code (hypothetical example): 

```go
var (
	// change the NewTypeValue to "name", "creatorFunc", "...traits"
	NullType = NewTypeValue("null_type", NativeToNull)
	NullSingleton = Null(types.Null)
)

func NativeToNull(input interface{}) ref.Val {
	return NullSingleton
}

type Null struct {
	types.Null
}

func (n Null) Equal(other ref.Val) ref.Val {
	if types.NullType != other.Type() {
		return types.False
	}
	return types.True
}
```

Then, when creating the cel environment:

```go
	env, err := cel.NewEnv(
		cel.Types(NullType),
	)
```

This has the added benefit of centralizing ref.Val generation from concrete types.  The `constsValue` func and `nativeToValue` func from planner and types repsectively can be consolidated to calling the `Value()` func from the type within `TypeProvider`.

The point that I haven't explored is creating a fast map that the current `nativeToValue` implementation defines, vs' looking up each type for attributes, or the API for each concrete ref.Type to create its Value. 

**Alternatives considered**

- Allowing built-in operators to be overridden
- Decorators.  I'm currently implementing this functionality by intercepting call expressions for operators, then checking types to see if overloads occur for builtins - and, if so, returning a custom InterpretableCall which returns a concrete value vs an error.

**Comment by TristonianJones** [comment]
The `cel.CustomTypeAdapter` option will let you provide a `ref.TypeAdapter` that can intercept the type conversion and supply your own `ref.Val` instances. Often people embed the default adapter into their custom one.

Let me know if your have any issues with this approach.

**Comment by tonyhb** [comment]
I tried this and have set both a `cel.CustomTypeAdapter` as well as a `cel.CustomTypeProvider` inside the environment, though they do not intercept consts.  It's sometimes common (for us) to have an expression testing null: `data.field_xyz == null`.  Unfortunately, you can't intercept the null in order to provide something that tests equality nicely.

**Comment by TristonianJones** [comment]
The easy thing to do seems to be to make the consts go through `NativeToValue`. I'm not opposed to making this change

**Comment by TristonianJones** [comment]
Honestly, we're going to overhaul equality this quarter too, so don't be surprised if the behavior you're looking for is basically what we end up implementing as the default. I think I filed an issue for something similar here in cel-spec as well. In the mean time, I can make the planning change sometime next week

**Comment by tonyhb** [comment]
Ah that's super interesting to hear, the refactor sounds fun.

I'm totally okay with the decorator approach we're using now (thanks for that tip earlier this year!), so no need to rush any changes out this week on my behalf, even though I very much appreciate it.  Especially as you already have a refactor planned and it's really not that pressing! :)
